### ISSUE TITLE
OTR sessions timing out before establishing

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/rocketchat#9]
A few months ago, OTR would successfully establish connections.

A few days ago, trying to connect between two "available/green status" RocketChat users does not notify the OTR recipient that a connection attempt it waiting for them to accept.  It just times out and fails on the sender end.

See example from conn attempt with @caggles 
![Screen Shot 2021-06-14 at 1 00 36 PM](https://user-images.githubusercontent.com/37681273/121963230-acfe6c00-cd1e-11eb-810a-41b2d3b3f66b.png)
![Screen Shot 2021-06-14 at 1 00 42 PM](https://user-images.githubusercontent.com/37681273/121963254-b4257a00-cd1e-11eb-898c-d41a0b95fb4d.png)

**Comment by jleach** [comment]
I think this is known issue in RC. I'll upgrade to 3.15.x in the next few days to see if that improves things.

Ref. https://github.com/RocketChat/Rocket.Chat/issues/20791

**Comment by hans4rc** [comment]
OTR works fine again with 3.15.0

**Comment by jleach** [comment]
Closing. Fixed via software upgrade.
